# Generated by Django 4.2 on 2023-04-12 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('contractor', models.CharField(max_length=500, null=True)),
                ('nomenclature', models.CharField(max_length=500, null=True)),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('price_production', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Цена на входе')),
                ('marginarity', models.CharField(max_length=500, null=True)),
                ('price_base', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Цена на выходе')),
                ('contractor_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Скидка контрагенту')),
                ('application', models.CharField(max_length=500, null=True)),
                ('payment', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Учётная таблица',
                'verbose_name_plural': 'Учётные таблицы',
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_sign', models.BooleanField(default=False)),
                ('executor_sign', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name': 'Связь со справочником',
                'verbose_name_plural': 'Связи со справочником',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='GuideParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('guide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_params', to='home.guide')),
            ],
            options={
                'verbose_name': 'Поле справочника',
                'verbose_name_plural': 'Поля справочника',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=home.models.upload_to, verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_sign', models.BooleanField(default=False)),
                ('executor_sign', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='home.act')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('labor_spend', models.TimeField(blank=True, null=True, verbose_name='Затраченное на операцию время')),
                ('labor_cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость часа работы')),
                ('consumables', models.ManyToManyField(blank=True, related_name='technical_tables', through='home.Connection', to='home.guideparams')),
            ],
            options={
                'verbose_name': 'Техкарта',
                'verbose_name_plural': 'Техкарты',
            },
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametr', to='home.act')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionTechAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество продукции')),
                ('accounting_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.accountingtable')),
                ('technical_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.technicaltable')),
            ],
            options={
                'verbose_name': 'Связь с техкартой',
                'verbose_name_plural': 'Связи с техкартами',
            },
        ),
        migrations.AddField(
            model_name='connection',
            name='guide_params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.guideparams'),
        ),
        migrations.AddField(
            model_name='connection',
            name='technical_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.technicaltable'),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('repeatable', models.BooleanField(default=False)),
                ('repeat_time', models.TimeField(blank=True, null=True, verbose_name='Повторять каждые')),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_customer', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_executor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Соглашение',
                'verbose_name_plural': 'Соглашения',
            },
        ),
        migrations.AddField(
            model_name='act',
            name='agreement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='home.agreement'),
        ),
        migrations.AddField(
            model_name='accountingtable',
            name='technicals',
            field=models.ManyToManyField(blank=True, related_name='accounting_tables', through='home.ConnectionTechAccount', to='home.technicaltable'),
        ),
    ]
