# Generated by Django 4.2 on 2023-04-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_accountingtable_technicals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicaltable',
            name='accounts',
        ),
        migrations.AddField(
            model_name='technicaltable',
            name='accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_tables', to='home.accountingtable'),
        ),
    ]
