# Generated by Django 4.2 on 2023-04-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_technicaltable_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicaltable',
            name='accounts',
        ),
        migrations.AddField(
            model_name='accountingtable',
            name='technicals',
            field=models.ManyToManyField(blank=True, related_name='accounting_tables', through='home.ConnectionTechAccount', to='home.technicaltable'),
        ),
    ]
