# Generated by Django 4.2 on 2023-04-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_technicaltable_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontechaccount',
            name='amount',
        ),
    ]
