# Generated by Django 4.2 on 2023-04-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_connectiontechaccount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingtable',
            name='marginarity',
            field=models.IntegerField(null=True, verbose_name='Маржинальность'),
        ),
    ]
